---
title: "GeONG"
author: "Linda Menk"
date: "2022-09-23"
output: rmdformats::material
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Tips  

Click on a function and press F1 for help  
Press Strg + Enter to run one line of code  
Press Strg + Up arrow + Enter to run a code chunk
Press Strg + Up arrow + C to comment out several lines  

# Install packages
knitr
rmdformats

# Load packages
```{r load packages}

# Installs all packages necessary for today
#install.packages(c("malariaAtlas","rnaturalearth","wpgpDownloadR","sf","terra","raster","dplyr","remotes","RColorBrewer","tmap","knitr","rmarkdown)) # Took me about 50 secs


#remotes::install_github("wpgp/wpgpDownloadR")

#Data access
library(malariaAtlas) # Malaria Atlas Project
library(rnaturalearth) # NaturalEarth
library(wpgpDownloadR) # Worldpop

#Mapping
library(tmap)
library(RColorBrewer)

#Geoprocessing
library(sf)
library(terra)
library(raster) #Elevation # Needed?
library(dplyr)

```

# Access data
## Administrative boundaries
```{r admin}

# Administrative boundaries of Burundi
# BDI <- afriadmin::afriadmin(country = "Burundi", level = 2)

BDI_shp <- malariaAtlas::getShp(ISO = "BDI", admin_level = "admin2")  

plot(BDI_shp)

#BDI_sf <- st_as_sf(BDI_shp)


```

## Malaria Atlas Project
```{r malariaAtlas}

# Downloads malaria indicator data
BDI_Pf2020 <- getRaster(surface = "Plasmodium  falciparum Incidence version 2020", shp = BDI_shp)

# Makes a basic plot of the downloaded malaria indicator data.
plot(BDI_Pf2020)

# Downloads malaria indicator data
BDI_access <- getRaster(surface = "Walking-only travel time to healthcare map without access to motorized transport", shp = BDI_shp)

# Makes a basic plot of the downloaded accessibility indicator data
plot(BDI_access)

```
# Worldpop
```{r Worldpop}

# Lists all datasets available for a selected country
wpgpListCountryDatasets(ISO3="BDI")

# Find out: What is the difference between the normal dataset, the UN adjusted dataset and the constrained/unconstrained dataset?

# Downloads the population indicator data (covariate) and saves it to disk
pop_path <- wpgpGetCountryDataset(ISO3 = "BDI",
                             covariate = "ppp_2020",
                             destDir = tempdir())

# Uses the "raster" function to load the downloaded data from disk
pop <- raster(pop_path)

# The downloaded data has a spatial resolution of 100m. For our analysis we do not need such fine data, it only slows our analysis down.
# Therefore, we aggregate the data by the factor 10 to get a spatial resolution of 1km. 
pop_agg <- aggregate(pop, fact = 10, fun = sum)

# Makes a basic plot of the population indicator data
plot(pop_agg)

```

```{r naturalearth}
# Download lakes from Naturalearthdat
# Optional
world_lakes <- ne_download(scale = 10, type = 'lakes', category = 'physical')

```

# Manipulate data

```{r pressure, echo=FALSE}

# Define AOI
# BDI is AOI

# Crop layers to AOI
# Function for crop
cropAOI <- function(data){
  st_as_sf(data) %>% 
  st_make_valid() %>% 
  st_crop(BDI_shp)
}

# To crop only the lakes in Burundi from the global lakes dataset
BDI_lakes <- cropAOI(world_lakes)

#----------------
# Analysis - Count Pop, Incidence, Avg. dist to healthcare per Admin area

# Convert administrative borders to a sf object
BDI_adm3 <- st_as_sf(BDI_shp)

# Sums the population per district
pop_sum <- terra::extract(pop_agg, BDI_adm3, fun = sum, ID = TRUE, na.rm = TRUE)
pop_district <- cbind(pop_sum,BDI_adm3)

# Mean plasmodium falciparum indicence per district
PF20_mean <- terra::extract(BDI_Pf2020, BDI_adm3, fun = mean, ID = TRUE, na.rm = TRUE)
Pf20_district <- cbind(PF20_mean,BDI_adm3)

# Mean distance to the nearest healthcare facility per district
access_mean <- terra::extract(BDI_access, BDI_adm3, fun = mean, ID = TRUE, na.rm = TRUE)
access_district <- cbind(access_mean,BDI_adm3)

# Bind all the indicators to the same geospatial outlines
BDI_district<-cbind(pop_district, Pf20_district, access_district)
```
# Visualize
```{r mapp}
library(tmap)
library(RColorBrewer)

tmap_mode("view")

pal <- c('#60b564','#fed400')

x <- tm_shape(BDI_district) +
  tm_polygons(col = "pop_sum", palette = pal, popup.vars = c("Pop"="pop_sum")) +
  tm_borders(lwd = 0.2) + 
  tm_layout(title = "Burundi") + 
  tm_shape(BDI_lakes) + 
  tm_fill(col = '#BFE1F4') + 
  tm_borders(lwd = 1, col = "black") 

y <- tm_shape(BDI_district) +
  tm_polygons(col = "access_mean", palette = pal, popup.vars = c("Access"="access_mean")) +
  tm_borders(lwd = 0.2) + 
  tm_shape(BDI_lakes) + 
  tm_fill(col = '#BFE1F4') + 
  tm_borders(lwd = 1, col = "black")

z <- tm_shape(BDI_district) +
  tm_polygons(col = "PF20_mean", palette = pal, popup.vars = c("Malaria incidence"="PF20_mean")) +
  tm_borders(lwd = 0.2) + 
  tm_shape(BDI_lakes) + 
  tm_fill(col = '#BFE1F4') + 
  tm_borders(lwd = 1, col = "black")

tmap_arrange(x,y,z)
```
```{r created composite indicator}

# Perform min-max normalization on population indicator
BDI_district$pop_norm <- (BDI_district$pop_sum - min(BDI_district$pop_sum))/(max(BDI_district$pop_sum) - min(BDI_district$pop_sum))

# Perform min-max normalization on malaria incidence indicator
BDI_district$pf_norm <- (BDI_district$PF20_mean - min(BDI_district$PF20_mean))/(max(BDI_district$PF20_mean) - min(BDI_district$PF20_mean))

# Perform min-max normalization on accessibility indicator
BDI_district$access_norm <- (BDI_district$access_mean - min(BDI_district$access_mean))/(max(BDI_district$access_mean) - min(BDI_district$access_mean))

# Sum all three sub-indicators 
BDI_district$composite_indicator <- (BDI_district$pop_norm + BDI_district$pf_norm + BDI_district$access_norm)/3

# Visualize composite indicator as a map
tm_shape(BDI_district) +
  tm_polygons(col = "composite_indicator", palette = pal, popup.vars = c("Risk index"="composite_indicator")) +
  tm_borders(lwd = 0.2) + 
  tm_layout(title = "Burundi") + 
  tm_shape(BDI_lakes) + 
  tm_fill(col = '#BFE1F4') + 
  tm_borders(lwd = 1, col = "black") 

```
